ALTER SESSION SET CONTAINER = JUDI_PDB;
SHOW CON_NAME;  -- should display JUDI_PDB
show user; -- JUDI_APP

-- creating tables:

CREATE TABLE USERS (
  ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME         VARCHAR2(50) UNIQUE NOT NULL,
  FULL_NAME        VARCHAR2(100),
  EMAIL            VARCHAR2(100),
  ROLE             VARCHAR2(30)
                    CHECK (ROLE IN ('CLERK','LAWYER','JUDGE','SUPREME_ADMIN')),
  CLEARANCE_LEVEL  VARCHAR2(20),
  CREATED_AT       DATE DEFAULT SYSDATE,
  UPDATED_AT       DATE
);

CREATE TABLE CASES (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CASE_NUMBER     VARCHAR2(30) UNIQUE NOT NULL,
  CASE_STATUS     VARCHAR2(30),
  TITLE           VARCHAR2(200),
  DESCRIPTION     CLOB,
  STATUS          VARCHAR2(30),
  SECURITY_LEVEL  VARCHAR2(30)
                  CHECK (SECURITY_LEVEL IN ('PUBLIC','ACTIVE','EVIDENCE','CLASSIFIED')),
  CREATED_AT      DATE DEFAULT SYSDATE,
  UPDATED_AT      DATE
);

CREATE TABLE EVIDENCE (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CASE_ID         NUMBER REFERENCES CASES(ID) ON DELETE CASCADE,
  EVIDENCE_TYPE   VARCHAR2(50),
  DESCRIPTION     CLOB,
  FILE_URL        VARCHAR2(255),
  SECURITY_LEVEL  VARCHAR2(30)
                  CHECK (SECURITY_LEVEL IN ('PUBLIC','ACTIVE','EVIDENCE','CLASSIFIED')),
  SUBMITTED_BY    NUMBER REFERENCES USERS(ID),
  SUBMITTED_AT    DATE DEFAULT SYSDATE
);

CREATE TABLE WITNESS (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FULL_NAME      VARCHAR2(100),
  STATEMENT      CLOB,
  CASE_ID        NUMBER REFERENCES CASES(ID) ON DELETE CASCADE,
  CONTACT_INFO   VARCHAR2(255),
  SECURITY_LEVEL VARCHAR2(30)
                  CHECK (SECURITY_LEVEL IN ('PUBLIC','ACTIVE','EVIDENCE','CLASSIFIED')),
  CREATED_AT     DATE DEFAULT SYSDATE,
  CREATED_BY     NUMBER REFERENCES USERS(ID)
);

CREATE TABLE ACCESS_LOG (
  ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID        NUMBER REFERENCES USERS(ID),
  TARGET_TYPE    VARCHAR2(50),
  TARGET_ID      NUMBER,
  ACCESS_TIME    DATE DEFAULT SYSDATE,
  ACCESS_RESULT  VARCHAR2(30),
  REASON         VARCHAR2(255)
);

/*
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ACCESS_LOG CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE WITNESS CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE EVIDENCE CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE CASES CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
*/